# Build and test
FROM node:16-alpine as restapiBase

COPY ./restapi /restapi
WORKDIR /restapi

RUN yarn install \
    && yarn build

# Production
FROM node:16-alpine

COPY ./restapi/.env /restapi/.env
COPY ./restapi/managers.json /restapi/managers.json
COPY ./restapi/restapi.yml /restapi/restapi.yml
COPY ./restapi/swagger.json /restapi/swagger.json
COPY ./restapi/package.json /restapi/package.json


COPY --from=restapiBase /restapi/dist /restapi/dist
WORKDIR /restapi

RUN yarn install --production

ENTRYPOINT ["yarn"]
CMD ["restapi"]
